-- Copyright (C) 1991-2010 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- PROGRAM		"Quartus II"
-- VERSION		"Version 9.1 Build 350 03/24/2010 Service Pack 2 SJ Full Version"
-- CREATED		"Mon Dec 13 19:29:45 2021"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY top2 IS 
	PORT
	(
		clk_50M :  IN  STD_LOGIC;
		EXT_X1 :  IN  STD_LOGIC;
		EXT_X2 :  IN  STD_LOGIC;
		EXT_X3 :  IN  STD_LOGIC;
		EXT_X4 :  IN  STD_LOGIC;
		EXT_X5 :  IN  STD_LOGIC;
		EXT_X6 :  IN  STD_LOGIC;
		RXD1 :  IN  STD_LOGIC;
		RXD2 :  IN  STD_LOGIC;
		EXT_IO15 :  IN  STD_LOGIC;
		EXT_IO3_COM_R1 :  IN  STD_LOGIC;
		EXT_IO4_COM_R2 :  IN  STD_LOGIC;
		EXT_IO5_RO2_485 :  IN  STD_LOGIC;
		EXT_IO7_CHG_ERR :  IN  STD_LOGIC;
		EXT_IO10_RO_485 :  IN  STD_LOGIC;
		EXT_IO11_CHK2 :  IN  STD_LOGIC;
		EXT_IO12_CHK1 :  IN  STD_LOGIC;
		RXD3_A :  IN  STD_LOGIC;
		EXT_IO21_AD_DO :  IN  STD_LOGIC;
		SDA :  INOUT  STD_LOGIC;
		SDA_LM75 :  INOUT  STD_LOGIC;
		SCL :  OUT  STD_LOGIC;
		SCL_LM75 :  OUT  STD_LOGIC;
		CTR_RLY1 :  OUT  STD_LOGIC;
		CTR_RLY2 :  OUT  STD_LOGIC;
		CTR_RLY3 :  OUT  STD_LOGIC;
		CTR_RLY4 :  OUT  STD_LOGIC;
		CTR_RLY5 :  OUT  STD_LOGIC;
		CTR_RLY6 :  OUT  STD_LOGIC;
		LED1 :  OUT  STD_LOGIC;
		LED2 :  OUT  STD_LOGIC;
		LED3 :  OUT  STD_LOGIC;
		LED4 :  OUT  STD_LOGIC;
		EXT_IO1_TX3 :  OUT  STD_LOGIC;
		EXT_IO6_DI2_485 :  OUT  STD_LOGIC;
		EXT_IO9_DI_485 :  OUT  STD_LOGIC;
		EXT_IO18_COM_T2 :  OUT  STD_LOGIC;
		EXT_IO19_AD_CLK_IN :  OUT  STD_LOGIC;
		EXT_IO20_AD_DI :  OUT  STD_LOGIC;
		EXT_IO22_AD_CS_IN :  OUT  STD_LOGIC;
		TX_A :  OUT  STD_LOGIC;
		EXT_IO14_TX1_A :  OUT  STD_LOGIC;
		EXT_IO16_TX2_A :  OUT  STD_LOGIC;
		EXT_IO13_TX5_A :  OUT  STD_LOGIC;
		EXT_IO8_CHG_EN :  OUT  STD_LOGIC;
		EXT_IO17_COM_T1 :  OUT  STD_LOGIC;
		EXT_IO2_TX4 :  OUT  STD_LOGIC
	);
END top2;

ARCHITECTURE bdf_type OF top2 IS 

COMPONENT ad_mcp3202
	PORT(CLK_50M : IN STD_LOGIC;
		 trig : IN STD_LOGIC;
		 DIN : IN STD_LOGIC;
		 AD_CS : OUT STD_LOGIC;
		 AD_CLK : OUT STD_LOGIC;
		 AD_DIN : OUT STD_LOGIC;
		 LK : OUT STD_LOGIC;
		 AD_DAT1 : OUT STD_LOGIC_VECTOR(11 DOWNTO 0);
		 AD_DAT2 : OUT STD_LOGIC_VECTOR(11 DOWNTO 0)
	);
END COMPONENT;

COMPONENT rst_g
	PORT(clk : IN STD_LOGIC;
		 RST : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT div_500
	PORT(clk : IN STD_LOGIC;
		 CLK2 : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT trig_100
	PORT(clk : IN STD_LOGIC;
		 trig : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT trig_rvs
	PORT(trig : IN STD_LOGIC;
		 rvs : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT level_edg
	PORT(Level_in : IN STD_LOGIC;
		 clk : IN STD_LOGIC;
		 Edg_out : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT dat_sel
	PORT(Aux : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 DatA1 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatA2 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatA3 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatA4 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatA5 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatB1 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatB2 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatB3 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatB4 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatB5 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatC1 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatC2 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatC3 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatC4 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatC5 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatD1 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatD2 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatD3 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatD4 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatD5 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatE1 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatE2 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatE3 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatE4 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatE5 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatF1 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatF2 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatF3 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatF4 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DatF5 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT1 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT2 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT3 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT4 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT5 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT mast_to_slave
	PORT(CLK : IN STD_LOGIC;
		 CLR_N : IN STD_LOGIC;
		 CMD : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 DAT1 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT3 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT5 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT7 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT9 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 LD : OUT STD_LOGIC;
		 DAT : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
	);
END COMPONENT;

COMPONENT en_tx_sel
	PORT(clk : IN STD_LOGIC;
		 TX : IN STD_LOGIC;
		 Grp : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 TX1 : OUT STD_LOGIC;
		 TX2 : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT mast_to_charger
	PORT(CLK : IN STD_LOGIC;
		 CLR_N : IN STD_LOGIC;
		 CMD : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 DAT_U : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 LD : OUT STD_LOGIC;
		 DAT : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
	);
END COMPONENT;

COMPONENT com_tx
	PORT(clk : IN STD_LOGIC;
		 LD : IN STD_LOGIC;
		 DAT : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 dout : OUT STD_LOGIC;
		 busy : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT cmd_aux_deal
	PORT(EN : IN STD_LOGIC;
		 Trig : IN STD_LOGIC;
		 CMD : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 CMD01 : OUT STD_LOGIC;
		 CMD02 : OUT STD_LOGIC;
		 CMD03 : OUT STD_LOGIC;
		 CMD04 : OUT STD_LOGIC;
		 CMD05 : OUT STD_LOGIC;
		 CMD06 : OUT STD_LOGIC;
		 CMD07 : OUT STD_LOGIC;
		 CMD08 : OUT STD_LOGIC;
		 CMD09 : OUT STD_LOGIC;
		 CMD0A : OUT STD_LOGIC;
		 CMD0B : OUT STD_LOGIC;
		 CMD0C : OUT STD_LOGIC;
		 CMD0D : OUT STD_LOGIC;
		 CMD0E : OUT STD_LOGIC;
		 CMD0F : OUT STD_LOGIC;
		 CMD10 : OUT STD_LOGIC;
		 CMD11 : OUT STD_LOGIC;
		 CMD12 : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT fpga_to_pc
	PORT(CLK : IN STD_LOGIC;
		 CLR_N : IN STD_LOGIC;
		 AUX : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 CMD : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 DAT1 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT3 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT5 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT7 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT9 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 Grp : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 LD : OUT STD_LOGIC;
		 DAT : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
	);
END COMPONENT;

COMPONENT lock_1
	PORT(clk : IN STD_LOGIC;
		 rst : IN STD_LOGIC;
		 clr : IN STD_LOGIC;
		 Q : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT com_rxd
	PORT(Din : IN STD_LOGIC;
		 clk : IN STD_LOGIC;
		 RST : IN STD_LOGIC;
		 CONFM : OUT STD_LOGIC;
		 Aux : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		 CMD : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		 dat1 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 dat3 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 dat5 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 dat7 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 dat9 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 Grp : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
	);
END COMPONENT;

COMPONENT mast_to_pfc
	PORT(CLK : IN STD_LOGIC;
		 CLR_N : IN STD_LOGIC;
		 CMD : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 DAT_I : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 DAT_U : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 LD : OUT STD_LOGIC;
		 DAT : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
	);
END COMPONENT;

COMPONENT clk_gen
	PORT(clk_50M : IN STD_LOGIC;
		 RST : IN STD_LOGIC;
		 clk_1M : OUT STD_LOGIC;
		 clk_100k : OUT STD_LOGIC;
		 clk_1ms : OUT STD_LOGIC;
		 clk_115200 : OUT STD_LOGIC
	);
END COMPONENT;

COMPONENT rly_ctr_8
	PORT(clk : IN STD_LOGIC;
		 CMD_R : IN STD_LOGIC;
		 RST : IN STD_LOGIC;
		 DAT : IN STD_LOGIC_VECTOR(7 DOWNTO 0);
		 R1 : OUT STD_LOGIC;
		 R2 : OUT STD_LOGIC;
		 R3 : OUT STD_LOGIC;
		 R4 : OUT STD_LOGIC;
		 R5 : OUT STD_LOGIC;
		 R6 : OUT STD_LOGIC;
		 R7 : OUT STD_LOGIC;
		 R8 : OUT STD_LOGIC;
		 RLY_st : OUT STD_LOGIC_VECTOR(7 DOWNTO 0)
	);
END COMPONENT;

COMPONENT lm75bd
	PORT(clk_1M : IN STD_LOGIC;
		 clk_1ms : IN STD_LOGIC;
		 SDA : INOUT STD_LOGIC;
		 SCL : OUT STD_LOGIC;
		 LK_O : OUT STD_LOGIC;
		 LED : OUT STD_LOGIC;
		 TEM1 : OUT STD_LOGIC_VECTOR(8 DOWNTO 0)
	);
END COMPONENT;

SIGNAL	AD_trig :  STD_LOGIC;
SIGNAL	AD_U1 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	AD_U2 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	clk_100k :  STD_LOGIC;
SIGNAL	clk_115200bps :  STD_LOGIC;
SIGNAL	clk_1M :  STD_LOGIC;
SIGNAL	clk_1ms :  STD_LOGIC;
SIGNAL	clk_500ms :  STD_LOGIC;
SIGNAL	CMD_01 :  STD_LOGIC;
SIGNAL	CMD_02 :  STD_LOGIC;
SIGNAL	CMD_03 :  STD_LOGIC;
SIGNAL	CMD_04 :  STD_LOGIC;
SIGNAL	CMD_05 :  STD_LOGIC;
SIGNAL	CMD_12 :  STD_LOGIC;
SIGNAL	CTR_state :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	Grp :  STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	PC_AUX :  STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	PC_CMD :  STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	RST :  STD_LOGIC;
SIGNAL	RX_DAT1 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	RX_DAT2 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	RX_DAT3 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	RX_DAT4 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	RX_DAT5 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	RX_OK :  STD_LOGIC;
SIGNAL	TEM :  STD_LOGIC_VECTOR(8 DOWNTO 0);
SIGNAL	TX_DAT1 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	TX_DAT2 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	TX_DAT3 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	TX_DAT4 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	TX_DAT5 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	TXD_trig :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_0 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_56 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_3 :  STD_LOGIC_VECTOR(0 TO 15);
SIGNAL	SYNTHESIZED_WIRE_57 :  STD_LOGIC_VECTOR(0 TO 15);
SIGNAL	SYNTHESIZED_WIRE_30 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_31 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_32 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_33 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_34 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_35 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_36 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_37 :  STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_38 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_39 :  STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_40 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_41 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_58 :  STD_LOGIC_VECTOR(0 TO 7);
SIGNAL	SYNTHESIZED_WIRE_43 :  STD_LOGIC_VECTOR(0 TO 7);
SIGNAL	SYNTHESIZED_WIRE_59 :  STD_LOGIC_VECTOR(0 TO 15);
SIGNAL	SYNTHESIZED_WIRE_50 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_51 :  STD_LOGIC_VECTOR(7 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_52 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_53 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_54 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_55 :  STD_LOGIC_VECTOR(7 DOWNTO 0);


BEGIN 
LED1 <= '0';
EXT_IO1_TX3 <= '1';
SYNTHESIZED_WIRE_3 <= "0000000000000000";
SYNTHESIZED_WIRE_57 <= "0000000000000000";
SYNTHESIZED_WIRE_32 <= '0';
SYNTHESIZED_WIRE_58 <= "00000000";
SYNTHESIZED_WIRE_43 <= "11111111";
SYNTHESIZED_WIRE_59 <= "0000000000000000";



b2v_inst : ad_mcp3202
PORT MAP(CLK_50M => clk_50M,
		 trig => AD_trig,
		 DIN => EXT_IO21_AD_DO,
		 AD_CS => EXT_IO22_AD_CS_IN,
		 AD_CLK => EXT_IO19_AD_CLK_IN,
		 AD_DIN => EXT_IO20_AD_DI,
		 AD_DAT1 => AD_U1(11 DOWNTO 0),
		 AD_DAT2 => AD_U2(11 DOWNTO 0));


b2v_inst1 : rst_g
PORT MAP(clk => clk_50M,
		 RST => RST);


b2v_inst10 : div_500
PORT MAP(clk => clk_1ms,
		 CLK2 => clk_500ms);


b2v_inst11 : trig_100
PORT MAP(clk => clk_1M,
		 trig => AD_trig);


b2v_inst12 : trig_rvs
PORT MAP(trig => SYNTHESIZED_WIRE_0,
		 rvs => LED3);



b2v_inst14 : level_edg
PORT MAP(Level_in => RX_OK,
		 clk => clk_115200bps,
		 Edg_out => SYNTHESIZED_WIRE_0);




SYNTHESIZED_WIRE_56 <= NOT(clk_500ms);




LED2 <= NOT(SYNTHESIZED_WIRE_56);



b2v_inst2 : dat_sel
PORT MAP(Aux => PC_AUX,
		 DatA1 => AD_U1,
		 DatA2 => AD_U2,
		 DatA3 => SYNTHESIZED_WIRE_3,
		 DatA4 => CTR_state,
		 DatA5 => SYNTHESIZED_WIRE_57,
		 DatB1 => SYNTHESIZED_WIRE_57,
		 DatB2 => SYNTHESIZED_WIRE_57,
		 DatB3 => SYNTHESIZED_WIRE_57,
		 DatB4 => SYNTHESIZED_WIRE_57,
		 DatB5 => SYNTHESIZED_WIRE_57,
		 DatC1 => SYNTHESIZED_WIRE_57,
		 DatC2 => SYNTHESIZED_WIRE_57,
		 DatC3 => SYNTHESIZED_WIRE_57,
		 DatC4 => SYNTHESIZED_WIRE_57,
		 DatC5 => SYNTHESIZED_WIRE_57,
		 DatD1 => SYNTHESIZED_WIRE_57,
		 DatD2 => SYNTHESIZED_WIRE_57,
		 DatD3 => SYNTHESIZED_WIRE_57,
		 DatD4 => SYNTHESIZED_WIRE_57,
		 DatD5 => SYNTHESIZED_WIRE_57,
		 DatE1 => SYNTHESIZED_WIRE_57,
		 DatE2 => SYNTHESIZED_WIRE_57,
		 DatE3 => SYNTHESIZED_WIRE_57,
		 DatE4 => SYNTHESIZED_WIRE_57,
		 DatE5 => SYNTHESIZED_WIRE_57,
		 DatF1 => SYNTHESIZED_WIRE_57,
		 DatF2 => SYNTHESIZED_WIRE_57,
		 DatF3 => SYNTHESIZED_WIRE_57,
		 DatF4 => SYNTHESIZED_WIRE_57,
		 DatF5 => SYNTHESIZED_WIRE_57);




b2v_inst22 : mast_to_slave
PORT MAP(CLK => SYNTHESIZED_WIRE_30,
		 CLR_N => SYNTHESIZED_WIRE_31,
		 CMD => PC_CMD,
		 DAT1 => RX_DAT1,
		 DAT3 => RX_DAT2,
		 DAT5 => RX_DAT3,
		 DAT7 => RX_DAT4,
		 DAT9 => RX_DAT5,
		 LD => SYNTHESIZED_WIRE_38,
		 DAT => SYNTHESIZED_WIRE_39);


SYNTHESIZED_WIRE_30 <= NOT(clk_115200bps);



SYNTHESIZED_WIRE_31 <= NOT(SYNTHESIZED_WIRE_32);



b2v_inst25 : en_tx_sel
PORT MAP(clk => clk_50M,
		 TX => SYNTHESIZED_WIRE_33,
		 Grp => Grp,
		 TX1 => EXT_IO17_COM_T1,
		 TX2 => EXT_IO18_COM_T2);


b2v_inst26 : mast_to_charger
PORT MAP(CLK => SYNTHESIZED_WIRE_34,
		 CLR_N => SYNTHESIZED_WIRE_35,
		 CMD => PC_CMD,
		 DAT_U => RX_DAT1,
		 LD => SYNTHESIZED_WIRE_50,
		 DAT => SYNTHESIZED_WIRE_51);


b2v_inst27 : com_tx
PORT MAP(clk => clk_115200bps,
		 LD => SYNTHESIZED_WIRE_36,
		 DAT => SYNTHESIZED_WIRE_37,
		 dout => EXT_IO2_TX4,
		 busy => LED4);


b2v_inst28 : cmd_aux_deal
PORT MAP(EN => RX_OK,
		 Trig => TXD_trig,
		 CMD => PC_CMD,
		 CMD01 => CMD_01,
		 CMD02 => CMD_02,
		 CMD03 => CMD_03,
		 CMD04 => CMD_04,
		 CMD12 => CMD_12);


b2v_inst29 : com_tx
PORT MAP(clk => clk_115200bps,
		 LD => SYNTHESIZED_WIRE_38,
		 DAT => SYNTHESIZED_WIRE_39,
		 dout => SYNTHESIZED_WIRE_33);


b2v_inst3 : fpga_to_pc
PORT MAP(CLK => SYNTHESIZED_WIRE_40,
		 CLR_N => SYNTHESIZED_WIRE_41,
		 AUX => SYNTHESIZED_WIRE_58,
		 CMD => SYNTHESIZED_WIRE_43,
		 DAT1 => SYNTHESIZED_WIRE_59,
		 DAT3 => SYNTHESIZED_WIRE_59,
		 DAT5 => SYNTHESIZED_WIRE_59,
		 DAT7 => SYNTHESIZED_WIRE_59,
		 DAT9 => SYNTHESIZED_WIRE_59,
		 Grp => SYNTHESIZED_WIRE_58,
		 LD => SYNTHESIZED_WIRE_36,
		 DAT => SYNTHESIZED_WIRE_37);


b2v_inst30 : lock_1
PORT MAP(clk => clk_50M,
		 rst => CMD_01,
		 clr => CMD_02);


b2v_inst31 : com_tx
PORT MAP(clk => clk_115200bps,
		 LD => SYNTHESIZED_WIRE_50,
		 DAT => SYNTHESIZED_WIRE_51,
		 dout => EXT_IO9_DI_485);


b2v_inst32 : com_rxd
PORT MAP(Din => RXD1,
		 clk => clk_115200bps,
		 RST => RST,
		 CONFM => RX_OK,
		 Aux => PC_AUX,
		 CMD => PC_CMD,
		 dat1 => RX_DAT1,
		 dat3 => RX_DAT2,
		 dat5 => RX_DAT3,
		 dat7 => RX_DAT4,
		 dat9 => RX_DAT5,
		 Grp => Grp);


SYNTHESIZED_WIRE_34 <= NOT(clk_115200bps);



SYNTHESIZED_WIRE_35 <= NOT(CMD_04);



b2v_inst35 : mast_to_pfc
PORT MAP(CLK => SYNTHESIZED_WIRE_52,
		 CLR_N => SYNTHESIZED_WIRE_53,
		 CMD => PC_AUX,
		 DAT_I => RX_DAT2,
		 DAT_U => RX_DAT1,
		 LD => SYNTHESIZED_WIRE_54,
		 DAT => SYNTHESIZED_WIRE_55);


b2v_inst36 : com_tx
PORT MAP(clk => clk_115200bps,
		 LD => SYNTHESIZED_WIRE_54,
		 DAT => SYNTHESIZED_WIRE_55,
		 dout => EXT_IO6_DI2_485);


SYNTHESIZED_WIRE_52 <= NOT(clk_115200bps);



SYNTHESIZED_WIRE_53 <= NOT(CMD_12);






b2v_inst43 : level_edg
PORT MAP(Level_in => clk_500ms,
		 clk => clk_115200bps,
		 Edg_out => TXD_trig);





b2v_inst6 : clk_gen
PORT MAP(clk_50M => clk_50M,
		 RST => RST,
		 clk_1M => clk_1M,
		 clk_100k => clk_100k,
		 clk_1ms => clk_1ms,
		 clk_115200 => clk_115200bps);


b2v_inst7 : rly_ctr_8
PORT MAP(clk => clk_50M,
		 CMD_R => CMD_03,
		 RST => RST,
		 DAT => RX_DAT1(15 DOWNTO 8),
		 R1 => CTR_RLY1,
		 R2 => CTR_RLY2,
		 R3 => CTR_RLY3,
		 R4 => CTR_RLY4,
		 R5 => CTR_RLY5,
		 R6 => CTR_RLY6,
		 RLY_st => CTR_state(15 DOWNTO 8));


b2v_inst73 : lm75bd
PORT MAP(clk_1M => clk_100k,
		 clk_1ms => clk_1ms,
		 SDA => SDA_LM75,
		 SCL => SCL_LM75);


SYNTHESIZED_WIRE_40 <= NOT(clk_115200bps);



SYNTHESIZED_WIRE_41 <= NOT(TXD_trig);



AD_U1(15 DOWNTO 12) <= "0000";
AD_U2(15 DOWNTO 12) <= "0000";
CTR_state(7 DOWNTO 0) <= "00000000";
END bdf_type;